In [3]:
from scoperty_utils import save_df_parquet,read_source_parquet,upsert_df
import pandas as pd
import datetime as dt


today = dt.date.today()

path = f'historyZone/scoperty-{str(today)}.parquet.gzip'

new_data = read_source_parquet(path)
new_data

,city,neighborhood,zip_code,street_name,street_number,floor,floor_location,door,property_type,construction_date,...,heating_type,has_energy_certificate,has_garage,has_parking,has_balcony,price,lon,lat,processing_date,construction_year
0,lopppp,Ludwigsfeld,90478,Schanzenstraße,13,NaN,None,NaN,multi_family_house,2014-02-09,...,None,None,None,False,None,999999999.0,11.099906,49.446582,2022-01-31 18:39:33.973226,2014
1,London,Ludwigsfeld,90478,Schanzenstraße,13,NaN,None,NaN,multi_family_house,2014-02-09,...,None,None,None,False,None,999999999.0,11.099906,49.446582,2022-01-31 18:39:33.973226,2014
2,Munchen,Ludwigsfeld,90478,Schanzenstraße,13,NaN,None,NaN,multi_family_house,2014-02-09,...,None,None,None,False,None,999999999.0,11.099906,49.446582,2022-01-31 18:39:33.973226,2014
3,Nürnberg,Ludwigsfeld,90478,Schanzenstraße,13,NaN,None,NaN,multi_family_house,2014-02-09,...,None,None,None,False,None,999999999.0,11.099906,49.446582,2022-01-31 18:39:33.973226,2014
4,Nürnberg,Marienvorstadt,90402,Hadermühle,6,NaN,None,NaN,multi_family_house,1987-10-19,...,None,None,None,False,None,1.0,11.088089,49.450603,2022-01-31 18:39:33.973226,1987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9998,Nürnberg,Buch,90427,Höfleser Hauptstraße,77,NaN,None,NaN,single_family_house,1978-10-05,...,None,None,None,False,None,448825.0,11.029574,49.488530,2022-01-31 18:39:33.973226,1978
9999,Nürnberg,Fischbach,90475,Am Brand,2,NaN,None,NaN,single_family_house,2033-03-18,...,None,None,None,True,None,768056.0,11.181802,49.427282,2022-01-31 18:39:33.973226,2033
10000,Nürnberg,St. Leonhard,90439,Schneppenhorststraße,11,NaN,None,NaN,multi_family_house,1969-04-22,...,None,None,None,False,None,332840.0,11.042111,49.439460,2022-01-31 18:39:33.973226,1969
10001,Nürnberg,Gaismannshof,90431,Dechsendorfer Straße,19,NaN,None,NaN,single_family_house,1932-11-19,...,None,None,None,False,None,405447.0,11.035186,49.450694,2022-01-31 18:39:33.973226,1932
10002,Nürnberg,Maiach,90451,Isarstraße,12,NaN,None,NaN,single_family_house,1984-09-04,...,None,None,None,False,None,752959.0,11.060945,49.408638,2022-01-31 18:39:33.973226,1984

In [ ]:
try:
        current_data = read_source_parquet(f'consumerZone/scoperty-properties.parquet.gzip')
    except:
        current_data = None

    def select_columns(df:pd.DataFrame):
            selected_columns = df[[
                    "city",
                    "neighborhood",
                    "zip_code",
                    "street_name",
                    "street_number",
                    "property_type",
                    "construction_date",
                    "number_of_units",
                    "living_area",
                    "total_area",
                    "has_parking",
                    "price",
                    "lon",
                    "lat"
                    ]]
            return selected_columns

    new_data = select_columns(new_data)

    merged = upsert_df(new_data,current_data,["city", "neighborhood", "zip_code", "street_name","street_number"])

    save_df_parquet(merged,'consumerZone','scoperty-properties')